# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TODOLEGAL
email: info@todolegal.app
description: >- # this means to ignore newlines until "baseurl:"
  Estos Términos y Condiciones regirán su acceso y uso del software como servicio (SaaS) TODOLEGAL (en adelante, los Servicios o SaaS). 
  TODOLEGAL es un Doing Business As (DBA) o nombre comercial de Glyphtech Codex LLC, una Compañía de Responsabilidad Limitada de Delaware (en adelante, la "Compañía") 
  y cualquier información, texto, gráficos, fotografías u otros materiales cargados, mostrados o descargados a través de los Servicios (en adelante colectivamente, el "Contenido"). 
  El mero acceso y / o uso de los Servicios y su uso de los Servicios significa la aceptación del cumplimiento de estos Términos de Uso. La Empresa se reserva el derecho
  de actualizar sin previo aviso el software TODOLEGAL, por lo que desde el momento de la aceptación de este documento, el usuario comprende y acepta dicha condición.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://policies.todolegal.app/" # the base hostname & protocol for your site, e.g. http://example.com
twitter: jekyllrb
github: jekyll

minima:
  social_links:
    instagram: todolegal.app
    facebook: todolegaltech
    twitter: todolegal1
    linkedin: todolegal

lang: es
languages:
  ["es", "en"]
  # Build settings
theme: minima
plugins:
  - jekyll-feed

  # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
